### ISSUE TITLE
Error when using with Nuxt.js

### ISSUE THREAD

**Issue by gerritvanaaken** [Aashu-Dubey/capacitor-statusbar-safe-area#10] opened 2023-08-07 21:56 UTC
When using within my Nuxt.js environment, I am getting an error message on `npm run dev`.

````
[nuxt] [request error] [unhandled] [500] HTMLElement is not defined
  at Object.<anonymous> (./node_modules/@aashu-dubey/capacitor-statusbar-safe-area/dist/plugin.cjs.js:38:31) 
````

When I remove "SafeAreaElement" from the plugin code, all is working well.(I do not need SafeSreaElement, only "getSafeAreaInsets"), so I could do a fork, but maybe you can have look into it.

Maybe it has something to do with TypeScript (or the lack of it?)

**Comment by Aashu-Dubey** [comment] 2023-08-09 19:27
Hi, I created a dummy Nuxt.js project with Capacitor and was able to reproduce this.

I'm not really sure about this behaviour in Nuxt to be honest, I could only find some issues with them suggesting [this solution](https://github.com/probil/vue-moveable/issues/294#issue-944971872) to bypass the error.

I've pushed some potential fix in the branch [fix/HTMLElement_nuxtjs_10](https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area/tree/fix/HTMLElement_nuxtjs_10), it would be great if you can give it a try and confirm if it fixes the issue for you, though I already tested in the dummy app mentioned above and it's working fine for me.

Thanks!

**Comment by gerritvanaaken** [comment] 2023-08-10 19:39
Still no luck. I downloaded your fixed branch, did `npm i` and `npm run build`, the result was still an error 500 on `npm run dev` in my Nuxt project. See attached Nuxt error as screenshot:

<img width="1229" alt="Bildschirmfoto 2023-08-10 um 21 36 01" src="https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area/assets/227735/a99b5940-df0b-4cf5-9006-abdca63267db">

**Comment by Aashu-Dubey** [comment] 2023-08-10 19:50
How are you using/installing the branch changes? please make sure the commit changes are present there, or maybe paste them manually in the node_modules to test?

When I tried this locally, it at least was working fine as long as I was not importing the `registerSafeAreaElement` function, means only importing `SafeArea` caused no error.

**Comment by gerritvanaaken** [comment] 2023-08-10 20:44
As I said, I downloaded a ZIP of the branch with the changes (There were there!), did `npm i` and `npm run build`, and the resulting `plugin.cjs.js` still threw an error. I only import `SafeAre`, not `SafeAreaElement`.

Maybe it’s my overly strictly configured TypeScript setup?

**Comment by Aashu-Dubey** [comment] 2023-08-10 21:29
I'm not really sure about the `npm i` part cause, this will then override `node_modules` with latest package version's changes, which will contain the branch changes.

I don't think typescript is the issue here, I was able to reproduce this in a initial NuxtJs project too, but got it working after the changes.

Do you have any idea why this behave this way in Nuxt, maybe cause of SSR, because of which window APIs are not available till complete rendering?

To test I would suggest you to just take commit changes and paste them directly to `node_modules/@aashu-dubey/capacitor-statusbar-safe-area` in relevant files, without running `npm i`.
or
as you said you downloaded zip, you can switch branch -> install the local package code following [this guide](https://capacitorjs.com/docs/plugins/workflow#local-testing)
it would show up like this
<img width="735" alt="image" src="https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area/assets/46301285/6ceaa2fd-d8f4-4964-af9a-4776d3832e10">

---
To give you can idea what I'm testing
<img width="866" alt="image" src="https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area/assets/46301285/d7255274-03e5-4ac6-bbd5-2024be141cd4">
<img width="1307" alt="image" src="https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area/assets/46301285/281dabba-6082-45be-b6d3-b4cd2e3676f6">

Have also tested on iOS by the way
(you can see insets printed at the top)
<img height="400" alt="image" src="https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area/assets/46301285/fe8678f9-08ad-45a0-b3d5-49aed10e043b">

**Comment by gerritvanaaken** [comment] 2023-08-12 20:32
I think I did everything correctly to have Nuxt use the new branch. See my terminal output from `npm run dev` below. Note that the line number of the error make sense for the new version, it is different from the "original" error line number. (When I use `npx nuxi generate` for my static output, the problem never occurred.)

I attach the dist folder that I generated with your new branch, maybe this helps:
[dist.zip](https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area/files/12328225/dist.zip)


````
[nuxt] [request error] [unhandled] [500] HTMLElement is not defined                                                            22:24:26
  at Object.<anonymous> (./node_modules/@aashu-dubey/capacitor-statusbar-safe-area/dist/plugin.cjs.js:60:31)  
  at Module._compile (node:internal/modules/cjs/loader:1255:14)  
  at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)  
  at Module.load (node:internal/modules/cjs/loader:1113:32)  
  at Module._load (node:internal/modules/cjs/loader:960:12)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)  
  at ModuleJob.run (node:internal/modules/esm/module_job:192:25)                                                               22:24:21
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[nuxt] [request error] [unhandled] [500] HTMLElement is not defined                                                            22:24:26
  at Object.<anonymous> (./node_modules/@aashu-dubey/capacitor-statusbar-safe-area/dist/plugin.cjs.js:60:31)  
  at Module._compile (node:internal/modules/cjs/loader:1255:14)  
  at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)  
  at Module.load (node:internal/modules/cjs/loader:1113:32)  
  at Module._load (node:internal/modules/cjs/loader:960:12)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)  
  at ModuleJob.run (node:internal/modules/esm/module_job:192:25)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[nuxt] [request error] [unhandled] [500] HTMLElement is not defined                                                            22:24:26
  at Object.<anonymous> (./node_modules/@aashu-dubey/capacitor-statusbar-safe-area/dist/plugin.cjs.js:60:31)  
  at Module._compile (node:internal/modules/cjs/loader:1255:14)  
  at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)  
  at Module.load (node:internal/modules/cjs/loader:1113:32)  
  at Module._load (node:internal/modules/cjs/loader:960:12)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)  
  at ModuleJob.run (node:internal/modules/esm/module_job:192:25)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
````

**Comment by Aashu-Dubey** [comment] 2023-08-18 21:59
I've temporarily pushed the dummy project that I was trying to test this issue [here](https://github.com/Aashu-Dubey/NuxtTest), can you please have a look and let me know if I'm testing properly here.

for package version update the package.json and copy the dist at the `node_modules`

For me the new branch changes are working fine in this project.

Regarding the issue I believe it's SSR related maybe, as browser APIs are not available on the server, see this blog for [reference](https://www.newline.co/@kchan/web-components-in-server-side-rendered-ssr-and-static-site-generated-ssg-in-nextjs-applications--6b2e93b2)

**Comment by Aashu-Dubey** [comment] 2023-08-19 19:25
Hi @gerritvanaaken 

The main reason you're getting this error is because of SSR, the browser APIs like HTMLElement are not available on the server, so to use this plugin and the functionalities within in your Nuxt.js app, you need to follow these steps:

1. Create a new file `safeArea.client.ts` (name as you wish) inside the `plugins` folder at the root.
we're suffixing with `.client` because we don't need this plugin on server side.
Now add below code inside the file

```ts
import * as SafeArea from "@aashu-dubey/capacitor-statusbar-safe-area";

export default defineNuxtPlugin(() => {
  return {
    provide: {
      CapSafeArea: SafeArea,
    },
  };
});
```

2. Now you can access the plugin anywhere in your Nuxt app like this:
```vue
<template>
  <div>
    Your Nuxt App
  </div>
</template>

<script setup lang="ts">
const { $CapSafeArea } = useNuxtApp();

const insets = await $CapSafeArea?.SafeArea?.getSafeAreaInsets();
console.log("getSafeAreaInsets", insets);

// $CapSafeArea?.registerSafeAreaElement();
</script>
```

And that's it, it should work fine after this, you don't even need the new branch I created.
(Feel free to tweak the names and other stuff to whatever works best for you, I just provided a minimal example)

Check out [this dummy app](https://github.com/Aashu-Dubey/NuxtTest) (will delete in a while) for a working example, and [this commit](https://github.com/Aashu-Dubey/NuxtTest/commit/3024a3ae7b1778c8d691d819ca63e2fdcf2d4c4a) for the changes required, it even is working fine with web component (`safe-area`) also now (the one that was causing you error).

I'm not sure how you're using the plugin, but doing above steps hopefully should fix the issue for you, as I have tested it now on Web as well as on Mobile.

---
There's an [official Capacitor blog](https://capacitorjs.jp/blog/integrating-capacitorjs-plugins-with-nuxtjs) regarding using Capacitor Plugins in a Nuxt app with SSR, avoiding any SSR related errors (like in your case).
It's an old blog that uses `inject` to make the plugin available globally, but that's deprecated now so the above steps are using the new approach according to the [current Nuxt documentation](https://nuxt.com/docs/guide/directory-structure/plugins#automatically-providing-helpers)

**Comment by Aashu-Dubey** [comment] 2023-08-19 19:31
Would really appreciate if you can try this and update if it fixes the issue for you, will also add a Nuxt.js example and details on Readme once you confirm.

**Comment by gerritvanaaken** [comment] 2023-08-19 19:55
You are unbelievable, thank you for all your work. Unfortunately I‘m on vacation right now. Hope I can check your plugin solution very soon!

**Comment by Aashu-Dubey** [comment] 2023-08-19 20:06
Alright, no issue, enjoy your vacation 🏖️

But make sure to update once you're back 😄

**Comment by gerritvanaaken** [comment] 2023-08-22 19:51
Very good! Including your project as proper Nuxt plugin within the `plugins` folder works smoothly and without errors now. I tried `npm run dev` and `npx nuxi generate` in SSR mode. All fine, thank you so much!

**Comment by Aashu-Dubey** [comment] 2023-08-22 20:08
Thanks for the update, now since we know it's not an issue, I'm gonna close this.

Will also update the README with this detail.

**Closed as completed by Aashu-Dubey** 2023-08-22 20:08 UTC
